/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaVista;

import capaLogica.Factura;
import capaLogica.Usuario;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ReporteFacturas extends javax.swing.JFrame {

    Usuario user;
    DefaultTableModel modeloTabla = new DefaultTableModel();
    
    public ReporteFacturas() {
        initComponents();
        modeloTabla = (DefaultTableModel)jTable1.getModel();
        this.setTitle("BMW - Reporte de Facturas");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/BMWLogo2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoF = new javax.swing.ButtonGroup();
        Titulo1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckPersonal = new javax.swing.JCheckBox();
        jCheckCorporativo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonSalir = new javax.swing.JLabel();
        jPanelBarra = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Bar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("Reporte de Facturas");
        getContentPane().add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jCheckPersonal.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroupTipoF.add(jCheckPersonal);
        jCheckPersonal.setForeground(new java.awt.Color(255, 255, 255));
        jCheckPersonal.setText("Personal");
        jCheckPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jCheckCorporativo.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroupTipoF.add(jCheckCorporativo);
        jCheckCorporativo.setForeground(new java.awt.Color(255, 255, 255));
        jCheckCorporativo.setText("Corporativo");
        jCheckCorporativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckCorporativoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckCorporativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.Factura", "Cliente", "Total Facturado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 740, 160));

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backMouse.png"))); // NOI18N
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalirMouseExited(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 100, 100));

        jPanelBarra.setBackground(new java.awt.Color(51, 51, 51));
        jPanelBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario");
        jPanelBarra.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 12, 149, -1));

        jLabelTipo.setBackground(new java.awt.Color(51, 51, 51));
        jLabelTipo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipo.setText("Tipo");
        jPanelBarra.add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 40, 149, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        jPanelBarra.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 12, -1, -1));

        getContentPane().add(jPanelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, 70));

        Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bar.png"))); // NOI18N
        getContentPane().add(Bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 240, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MantenimientoExtra.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setUser(Usuario user) {
        this.user = user;
    }
    private void jCheckPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckPersonalActionPerformed
      try{
           modeloTabla.setRowCount(0);//Limpia la tabla
            Object[] datos = new Object[3];

            ArrayList<Factura> lista = Factura.listadoFacturas();
            for (int i = 0; i < lista.size(); i++) {
                if(lista.get(i).getCliente().getTipo().equalsIgnoreCase("Personal")){
                    datos[0] = lista.get(i).getNumeroFactura();
                    datos[1] = lista.get(i).getCliente().getNombre();
                    datos[2] = "$"+lista.get(i).calculaTotalAuto();
                    
                    modeloTabla.addRow(datos);//Agrega el arreglo como una nueva fila de la tabla
                }

            }

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al llenar la tabla \n"
                + "el programa se cerrará consulte con el administrador\n"
                + e.toString());
        }
    }//GEN-LAST:event_jCheckPersonalActionPerformed

    private void jCheckCorporativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckCorporativoActionPerformed
        try{
           modeloTabla.setRowCount(0);//Limpia la tabla
            Object[] datos = new Object[3];

            ArrayList<Factura> lista = Factura.listadoFacturas();
            for (int i = 0; i < lista.size(); i++) {
                if(lista.get(i).getCliente().getTipo().equalsIgnoreCase("Corporativo")){
                    datos[0] = lista.get(i).getNumeroFactura();
                    datos[1] = lista.get(i).getCliente().getNombre();
                    datos[2] = "$"+lista.get(i).calculaTotalAuto();
                    
                    modeloTabla.addRow(datos);//Agrega el arreglo como una nueva fila de la tabla
                }

            }

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al llenar la tabla \n"
                + "el programa se cerrará consulte con el administrador\n"
                + e.toString());
        }
    }//GEN-LAST:event_jCheckCorporativoActionPerformed

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_botonSalirMouseClicked

    private void botonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseEntered
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png")));
    }//GEN-LAST:event_botonSalirMouseEntered

    private void botonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseExited
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backMouse.png")));
    }//GEN-LAST:event_botonSalirMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jLabelUsuario.setText(user.getNom());
        jLabelTipo.setText(user.getTipo().toString());
        llenarTabla();
    }//GEN-LAST:event_formWindowOpened

    private void llenarTabla(){
        try{
           modeloTabla.setRowCount(0);//Limpia la tabla
            Object[] datos = new Object[3];

            ArrayList<Factura> lista = Factura.listadoFacturas();
            for (int i = 0; i < lista.size(); i++) {
                
                    datos[0] = lista.get(i).getNumeroFactura();
                    datos[1] = lista.get(i).getCliente().getNombre();
                    datos[2] = "$"+lista.get(i).calculaTotalAuto();
                    
                    modeloTabla.addRow(datos);//Agrega el arreglo como una nueva fila de la tabla
                

            }

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al llenar la tabla \n"
                + "el programa se cerrará consulte con el administrador\n"
                + e.toString());
        }
    }
    
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel botonSalir;
    private javax.swing.ButtonGroup buttonGroupTipoF;
    private javax.swing.JCheckBox jCheckCorporativo;
    private javax.swing.JCheckBox jCheckPersonal;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelBarra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
